# Generated by Django 2.2.4 on 2019-09-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    def set_new_building(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            flat.new_building = True if flat.construction_year >= 2015 else False
            flat.save()

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building)
    ]


