# Generated by Django 2.2.5 on 2019-09-05 18:09

from django.db import migrations
from phonenumbers import parse, format_number, PhoneNumberFormat, is_valid_number


class Migration(migrations.Migration):

    def normalize_phone_numbers(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            normalized_number = parse(flat.owners_phonenumber, 'RU')
            flat.owner_phone_pure = format_number(normalized_number, PhoneNumberFormat.E164) if is_valid_number(normalized_number) else None
            flat.save()

    dependencies = [
        ('property', '0008_auto_20190905_2108'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]
