# Generated by Django 2.2.5 on 2019-09-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    def copy_owners(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')

        for flat in Flat.objects.all():
            Owner.objects.get_or_create(name=flat.owner, owners_phonenumber=flat.owners_phonenumber, owner_phone_pure=flat.owner_phone_pure)

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(copy_owners)
    ]
