# Generated by Django 2.2.5 on 2019-09-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    def connect_owners_and_flas(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')

        for owner in Owner.objects.all():
            owner.flats.set(Flat.objects.filter(owner=owner.name, owners_phonenumber=owner.owners_phonenumber))

    dependencies = [
        ('property', '0012_auto_20190909_2134'),
    ]

    operations = [
        migrations.RunPython(connect_owners_and_flas)
    ]
